name: Swift

on: [push]

jobs:
  build:
    name: Build swift app
    
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - uses: fwal/setup-swift@v1
      - name: Get swift version
        run: swift --version
      - name: Build
        working-directory: ./Bitwarden
        run: swift build
      - name: Run tests
        working-directory: ./Bitwarden
        run: swift test
